[build]
rustflags = ["-C", "link-arg=-Wl,-rpath,@executable_path/../lib"]

[env]
# INSIGHTFACE_PATH = "/Users/<path>/insightface/cpp-package/inspireface/build/inspireface-macos/InspireFace"
# Enable the setting below to generate documentation locally
# /!\ Disable the variable DOCS_RS to run the unit tests
# DOCS_RS = "false"
